### ISSUE TITLE
Rapihkan Struktur Kode /Display

### ISSUE THREAD

**Issue by brain90** [brain90/jam-masjid#6]
- [ ] Buat agar kode di display/index.php menjadi rapih sehingga lebih mudah dimaintain

**Comment by ShikaaDhia** [comment]
om saya mau nanya, ini berarti saya hanya merapihkan kode" nya biar gambang kalo dibaca ya?

**Comment by brain90** [comment]
Ya shika, skrg kan script js-nya masih campur aduk di satu tempat.  Pindahkan baris 173 s.d 532 ke berkas display.js ya. Selanjutnya tinggal direfer spt biasa dgn :
```html
<script type="text/javascript" src="js/jdisplay.js"></script>
```

**Comment by ShikaaDhia** [comment]
ohh oke om terima kasih

**Comment by brain90** [comment]
Agar beautiful, format code-nya menggunakan extension prettier y :

![image](https://github.com/brain90/jam-masjid/assets/858382/fdc90298-30c9-46ed-8eb0-f8154c96a950)
